[workspace]
resolver = "3"
members = ["main_crate", "types"]


[workspace.dependencies]
actix-web = "4.11.0"
serde = "1.0.219"
serde_json = "1.0.140"
sqlx = { version = "0.8.6", features = ["runtime-async-std-native-tls", "postgres", "chrono", "uuid"] }
