[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
uuid = { version = "1.17.0", features = ["serde", "v4"] }
sqlx = { workspace = true}
serde ={ workspace = true }
serde_json ={ workspace = true }
dotenvy = "0.15.7"
