[book]
authors = ["JusMe"]
language = "en"
src = "src"
title = "Actix Service Guide"

[output.html.playground]
runnable = false

[output.html]
additional-css = ["custom.css"]
additional-js = ["script.js"]
default-theme = "ayu"
copyable = true

[preprocessor.copy-assets]
command = "bash"
args = ["-c", "cp -r data/sample.json book/data"]
